#!/bin/bash

export DEBIAN_SYS_MAINT_PASSWORD=${DEBIAN_SYS_MAINT_PASSWORD:-$(pwgen -s 15 1)}
export ICINGA_PASSWORD=${ICINGA_PASSWORD:-$(pwgen -s 15 1)}
export IDO_PASSWORD=${IDO_PASSWORD:-$(pwgen -s 15 1)}
export ICINGAWEB2_PASSWORD=${ICINGAWEB2_PASSWORD:-$(pwgen -s 15 1)}
export DIRECTOR_PASSWORD=${DIRECTOR_PASSWORD:-$(pwgen -s 15 1)}
export DIRECTOR_API_PASSWORD=${DIRECTOR_API_PASSWORD:-$(pwgen -s 15 1)}
export ICINGAWEB2_ADMIN_USER=${ICINGAWEB2_ADMIN_USER:-"icingaadmin"}
export ICINGAWEB2_ADMIN_PASS=${ICINGAWEB2_ADMIN_PASS:-"icinga"}
export ICINGAWEB2_ADMIN_PASS_HASH=$(openssl passwd -1 "${ICINGAWEB2_ADMIN_PASS}")
export ICINGA2_FEATURE_DIRECTOR_PASS=${ICINGA2_FEATURE_DIRECTOR_PASS:-$(pwgen -s 15 1)}

if [ -f /opt/custom_run ]; then
    chmod u+x /opt/custom_run
    echo "=>executing /opt/custom_run"
    /opt/custom_run
fi

/opt/setup/apache2
/opt/setup/mysql
/opt/setup/icinga2
/opt/setup/graphite
/opt/setup/icingaweb2
/opt/setup/icingaweb2-director
/opt/setup/icingaweb2-graphite

cat <<-END

===================================================================
MySQL user 'root' has no password but only allows local connections
MySQL user 'debian-sys-maint' password set to ${DEBIAN_SYS_MAINT_PASSWORD}
MySQL user 'icinga' password set to ${ICINGA_PASSWORD}
MySQL user 'icinga2-ido-mysq' password set to ${IDO_PASSWORD}
MySQL user 'icingaweb2' password set to ${ICINGAWEB2_PASSWORD}
MySQL user 'director' password set to ${DIRECTOR_PASSWORD}
Director API password set to ${DIRECTOR_API_PASSWORD}

$(
if [ "${ICINGA2_FEATURE_GRAPHITE}" == "true" ] || [ "${ICINGA2_FEATURE_GRAPHITE}" == "1" ]; then
	echo "Graphite writer enabled and sending data to carbon agent at: ${ICINGA2_FEATURE_GRAPHITE_HOST}:${ICINGA2_FEATURE_GRAPHITE_PORT}"
fi
)

Icinga Web 2 (/icingaweb2) default credentials: ${ICINGAWEB2_ADMIN_USER}:${ICINGAWEB2_ADMIN_PASS}
===================================================================

Starting Supervisor.
END

/usr/bin/supervisord -c /etc/supervisor/conf.d/icinga2.conf > /dev/null
