#!/bin/bash

ISSET_IDO_PASSWORD=${IDO_PASSWORD:+<set via env variable>}
ISSET_ICINGAWEB2_PASSWORD=${ICINGAWEB2_PASSWORD:+<set via env variable>}
ISSET_DIRECTOR_PASSWORD=${DIRECTOR_PASSWORD:+<set via env variable>}
ISSET_DIRECTOR_API_PASSWORD=${DIRECTOR_API_PASSWORD:+<set via env variable>}
ISSET_ICINGAWEB2_ADMIN_PASS=${ICINGAWEB2_ADMIN_PASS:+<set via env variable>}

export IDO_PASSWORD=${IDO_PASSWORD:-$(pwgen -s 15 1)}
export ICINGAWEB2_PASSWORD=${ICINGAWEB2_PASSWORD:-$(pwgen -s 15 1)}
export DIRECTOR_PASSWORD=${DIRECTOR_PASSWORD:-$(pwgen -s 15 1)}
export DIRECTOR_API_PASSWORD=${DIRECTOR_API_PASSWORD:-$(pwgen -s 15 1)}
export ICINGAWEB2_ADMIN_USER=${ICINGAWEB2_ADMIN_USER:-"icingaadmin"}
export ICINGAWEB2_ADMIN_PASS=${ICINGAWEB2_ADMIN_PASS:-"icinga"}
export ICINGAWEB2_ADMIN_PASS_HASH=$(openssl passwd -1 "${ICINGAWEB2_ADMIN_PASS}")
export ICINGA2_FEATURE_DIRECTOR_PASS=${ICINGA2_FEATURE_DIRECTOR_PASS:-$(pwgen -s 15 1)}

run-parts --lsbsysinit -- /opt/setup

cat <<-END

===================================================================
MySQL user 'root' has no password but only allows local connections
MySQL user 'icinga2-ido-mysq' password set to ${ISSET_IDO_PASSWORD:-$IDO_PASSWORD}
MySQL user 'icingaweb2' password set to ${ISSET_ICINGAWEB2_PASSWORD:-$ICINGAWEB2_PASSWORD}
MySQL user 'director' password set to ${ISSET_DIRECTOR_PASSWORD:-$DIRECTOR_PASSWORD}
Director API password set to ${ISSET_DIRECTOR_API_PASSWORD:-$DIRECTOR_API_PASSWORD}

$(
if [ "${ICINGA2_FEATURE_GRAPHITE}" == "true" ] || [ "${ICINGA2_FEATURE_GRAPHITE}" == "1" ]; then
	echo "Graphite writer enabled and sending data to carbon agent at: ${ICINGA2_FEATURE_GRAPHITE_HOST}:${ICINGA2_FEATURE_GRAPHITE_PORT}"
fi
)

Icinga Web 2 (/icingaweb2) default credentials: ${ICINGAWEB2_ADMIN_USER}:${ISSET_ICINGAWEB2_ADMIN_PASS:-$ICINGAWEB2_ADMIN_PASS}
===================================================================

Starting Supervisor.
END

icinga2 daemon --validate

/usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
trap "supervisorctl shutdown && wait" SIGTERM
wait
