#!/bin/bash

set -e

initfile=/etc/icinga2.init

chmod 1777 /tmp

# chown directories and files that might be coming from volumes
chown -R mysql:mysql /var/lib/mysql
chown -R nagios:root /etc/icinga2
chown nagios:nagios /etc/icinga2/features-available/ido-mysql.conf
chown -R nagios:nagios /var/lib/icinga2
chown -R root:root /etc/icinga-web
chown root:www-data /etc/icinga-web/conf.d/module_reporting.xml /etc/icinga-web/conf.d/auth.xml /etc/icinga-web/conf.d/access.xml /etc/icinga-web/conf.d/database-web.xml /etc/icinga-web/conf.d/databases.xml
chown root:icingaweb2 /etc/icingaweb2
chmod 2770 /etc/icingaweb2
chown -R www-data:icingaweb2 /etc/icingaweb2/*
find /etc/icingaweb2 -type f -name "*.ini" -exec chmod 660 {} \;
find /etc/icingaweb2 -type d -exec chmod 2770 {} \;


if [ ! -f "${initfile}" ]; then

# Passwords...
DEBIAN_SYS_MAINT_PASSWORD=${DEBIAN_SYS_MAINT_PASSWORD:-$(pwgen -s 15 1)}
ICINGA_PASSWORD=${ICINGA_PASSWORD:-$(pwgen -s 15 1)}
IDO_PASSWORD=${IDO_PASSWORD:-$(pwgen -s 15 1)}
ICINGA_WEB_PASSWORD=${ICINGA_WEB_PASSWORD:-$(pwgen -s 15 1)}
ICINGAWEB2_PASSWORD=${ICINGAWEB2_PASSWORD:-$(pwgen -s 15 1)}

#icinga2 options
#icinga2-enable-feature ido-mysql >> /dev/null
if [[ -L /etc/icinga2/features-enabled/ido-mysql.conf ]]; then echo "Symlink for /etc/icinga2/features-enabled/ido-mysql.conf exists already...skipping"; else ln -s /etc/icinga2/features-available/ido-mysql.conf /etc/icinga2/features-enabled/ido-mysql.conf; fi
#icinga2-enable-feature livestatus >> /dev/null
if [[ -L /etc/icinga2/features-enabled/livestatus.conf ]]; then echo "Symlink for /etc/icinga2/features-enabled/livestatus.conf exists already... skipping"; else ln -s /etc/icinga2/features-available/livestatus.conf /etc/icinga2/features-enabled/livestatus.conf; fi
#icinga2-enable-feature compatlog >> /dev/null
if [[ -L /etc/icinga2/features-enabled/compatlog.conf ]]; then echo "Symlink for /etc/icinga2/features-enabled/compatlog.conf exists already... skipping"; else ln -s /etc/icinga2/features-available/compatlog.conf /etc/icinga2/features-enabled/compatlog.conf; fi
#icinga2-enable-feature command >> /dev/null
if [[ -L /etc/icinga2/features-enabled/command.conf ]]; then echo "Symlink for /etc/icinga2/features-enabled/command.conf exists already...skipping"; else ln -s /etc/icinga2/features-available/command.conf /etc/icinga2/features-enabled/command.conf; fi

usermod -a -G nagios www-data >> /dev/null

update_user_password () {
   (
   echo "UPDATE mysql.user SET password=PASSWORD('${2}') WHERE user='${1}';"
   echo "FLUSH PRIVILEGES;"
   echo "quit"
   ) |
   mysql
}

echo "=>Initializing databases and icinga2 configurations."
echo "=>This may take a few minutes"
/etc/init.d/mysql start

# Set debian-sys-maint password
update_user_password debian-sys-maint ${DEBIAN_SYS_MAINT_PASSWORD}
sed -i 's,password\ \=\ .*,password\ \=\ '${DEBIAN_SYS_MAINT_PASSWORD}',g' /etc/mysql/debian.cnf

# icinga
(
    echo "CREATE DATABASE IF NOT EXISTS icinga;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga.* TO 'icinga'@'localhost' IDENTIFIED BY '${ICINGA_PASSWORD}';"
    echo "quit"
) |
mysql
mysql -f icinga < /usr/share/icinga2-ido-mysql/schema/mysql.sql >> /opt/icinga2-ido-mysql-schema.log 2>&1
sed -i 's,<resource name="icinga_pipe">.*</resource>,<resource name="icinga_pipe">/run/icinga2/cmd/icinga2.cmd</resource>,g' /etc/icinga-web/conf.d/access.xml
sed -i 's/password \= \".*\"/password \= \"'${IDO_PASSWORD}'\"/g' /etc/icinga2/features-available/ido-mysql.conf
sed -i 's/user =\ \".*\"/user =\ \"icinga2-ido-mysq\"/g' /etc/icinga2/features-available/ido-mysql.conf
sed -i 's/database =\ \".*\"/database =\ \"icinga2idomysql\"/g' /etc/icinga2/features-available/ido-mysql.conf

(
    echo "CREATE DATABASE IF NOT EXISTS icinga2idomysql;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga2idomysql.* TO 'icinga2-ido-mysq'@'localhost' IDENTIFIED BY '${IDO_PASSWORD}';"
    echo "quit"
) |
mysql
mysql -f icinga2idomysql < /usr/share/dbconfig-common/data/icinga2-ido-mysql/install/mysql >> /opt/icinga2-ido-mysql-schema.log 2>&1

(
    echo "CREATE DATABASE IF NOT EXISTS icinga_web;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga_web.* TO 'icinga_web'@'localhost' IDENTIFIED BY '${ICINGA_WEB_PASSWORD}';"
    echo "quit"
) |
mysql
mysql -f icinga_web < /usr/share/dbconfig-common/data/icinga-web/install/mysql >> /opt/icinga-web-schema.log 2>&1
sed -i 's/mysql\:\/\/icinga_web\:.*\@localhost/mysql\:\/\/icinga_web\:'${ICINGA_WEB_PASSWORD}'\@localhost/g' /etc/icinga-web/conf.d/database-web.xml
sed -i 's/mysql\:\/\/.*\@localhost\/icinga.*</mysql\:\/\/icinga2-ido-mysq:'${IDO_PASSWORD}'\@localhost\/icinga2idomysql</g' /etc/icinga-web/conf.d/database-ido.xml
sed -i 's,mysql://icinga_web:.*@localhost,mysql://icinga_web:'${ICINGA_WEB_PASSWORD}'@localhost,g' /etc/icinga-web/conf.d/databases.xml
sed -i 's,mysql://icinga:.*@localhost,mysql://icinga:'${ICINGA_PASSWORD}'@localhost,g' /etc/icinga-web/conf.d/databases.xml

#icingaweb2
(
    echo "CREATE DATABASE IF NOT EXISTS icingaweb2;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icingaweb2.* TO 'icingaweb2'@'localhost' IDENTIFIED BY '${ICINGAWEB2_PASSWORD}';"
    echo "quit"
) |
mysql
mysql -f icingaweb2 < /usr/share/icingaweb2/etc/schema/mysql.schema.sql >> /opt/icingaweb2-schema.log 2>&1
ICINGAADMIN_PASSWORD=`openssl passwd -1 "icinga"`
(
    echo "USE icingaweb2;"
    echo "INSERT IGNORE INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '${ICINGAADMIN_PASSWORD}');"
    echo "quit"
) |
mysql
if [[ -L /etc/icingaweb2/enabledModules/monitoring ]]; then echo "Symlink for /etc/icingaweb2/enabledModules/monitoring exists already...skipping"; else ln -s /etc/icingaweb2/modules/monitoring /etc/icingaweb2/enabledModules/monitoring; fi
if [[ -L /etc/icingaweb2/enabledModules/doc ]]; then echo "Symlink for /etc/icingaweb2/enabledModules/doc exists already...skipping"; else ln -s /etc/icingaweb2/modules/doc /etc/icingaweb2/enabledModules/doc; fi
sed -i 's,icingaweb2_changeme,'${ICINGAWEB2_PASSWORD}',g' /etc/icingaweb2/resources.ini
sed -i 's,icinga2-ido-mysq_changeme,'${IDO_PASSWORD}',g' /etc/icingaweb2/resources.ini
mkdir -p /var/log/icingaweb2
chown www-data:adm /var/log/icingaweb2

/etc/init.d/mysql stop

echo -e "\n\n\n"
echo "==================================================================="
echo "MySQL user 'root' has no password but only allows local connections"
echo "MySQL user 'debian-sys-maint' password set to ${DEBIAN_SYS_MAINT_PASSWORD}"
echo "MySQL user 'icinga' password set to ${ICINGA_PASSWORD}"
echo "MySQL user 'icinga2-ido-mysq' password set to ${IDO_PASSWORD}"
echo "MySQL user 'icinga-web' password set to ${ICINGA_WEB_PASSWORD}"
echo "MySQL user 'icingaweb2' password set to ${ICINGAWEB2_PASSWORD}"
echo "==================================================================="

touch ${initfile}
fi

echo "Starting Supervisor.  You can safely CTRL-C and the container will continue to run with or without the -d (daemon) option"
/usr/bin/supervisord >> /dev/null
