#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down apache2"
    /etc/init.d/apache2 stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting apache2"

/etc/init.d/apache2 start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u www-data apache2 > /dev/null; do sleep 5; done
