#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down icinga2"
    /etc/init.d/icinga2 stop
}

echo "`date +"%d.%m.%Y %T.%3N"` - Starting icinga2"

/etc/init.d/icinga2 start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u nagios icinga2 > /dev/null; do sleep 5; done
