#!/bin/bash

env
set -x

/etc/init.d/mysql start

(
    echo "CREATE DATABASE icinga;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga.* TO 'icinga'@'localhost' IDENTIFIED BY 'icinga';"
    echo "quit"
) |
mysql

mysql icinga < /usr/share/icinga2-ido-mysql/schema/mysql.sql

icinga2-enable-feature ido-mysql
icinga2-enable-feature livestatus
icinga2-enable-feature compatlog
icinga2-enable-feature command
usermod -a -G nagios www-data

IDOPASS=`cat /etc/icinga2/features-enabled/ido-mysql.conf | grep password  | cut -d\" -f2`
sed -i 's/password \= \".*\"/password \= \"'${IDOPASS}'\"/g' /etc/icinga2/features-enabled/ido-mysql.conf

(
    echo "CREATE DATABASE icinga2idomysql;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga2idomysql.* TO 'icinga2-ido-mysq'@'localhost' IDENTIFIED BY '${IDOPASS}';"
    echo "quit"
) |
mysql
mysql icinga2idomysql < /usr/share/dbconfig-common/data/icinga2-ido-mysql/install/mysql

sed -i 's/mysql\:\/\/icinga_web\:.*\@localhost/mysql\:\/\/icinga_web\:icinga_web\@localhost/g' /etc/icinga-web/conf.d/database-web.xml
sed -i 's/mysql\:\/\/.*\@localhost\/icinga/mysql\:\/\/icinga2-ido-mysq:'${IDOPASS}'\@localhost\/icinga2idomysql/g' /etc/icinga-web/conf.d/database-ido.xml
sed -i 's,<resource name="icinga_pipe">.*</resource>,<resource name="icinga_pipe">/run/icinga2/cmd/icinga2.cmd</resource>,g' /etc/icinga-web/conf.d/access.xml
(
    echo "CREATE DATABASE icinga_web;"
    echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icinga_web.* TO 'icinga_web'@'localhost' IDENTIFIED BY 'icinga_web';"
    echo "quit"
) |
mysql
mysql icinga_web < /usr/share/dbconfig-common/data/icinga-web/install/mysql

/etc/init.d/mysql stop
