#!/bin/bash

function shutdown()
{
    echo "`date +"%d.%m.%Y %T.%3N"` - Shutting down apache2"
    /etc/init.d/apache2 stop
}

# Enable SSL support if certificates are mounted
if [ -f /etc/apache2/ssl/icinga2.crt -a -f /etc/apache2/ssl/icinga2.key ]; then

    # If there is no chain needed, we have to generate an empty
    # file with a single line to interpret it correctly as "no chain"
    if [ ! -f /etc/apache2/ssl/icinga2.chain ]; then
        echo > /etc/apache2/ssl/icinga2.chain
    fi
    a2enmod ssl
    a2ensite docker-ssl
else
    a2dissite docker-ssl
fi

echo "`date +"%d.%m.%Y %T.%3N"` - Starting apache2"

/etc/init.d/apache2 start

# Allow any signal which would kill a process to stop server
trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -u www-data apache2 > /dev/null; do sleep 5; done
