#!/bin/bash

. /opt/helpers

service icinga2 start

# Kickstart is only possible after icinga2 start -> not in setup script
if    evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR}" \
   && evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR_KICKSTART}"; then
	icingacli director kickstart run
fi

# Allow any signal which would kill a process to stop server
trap "service icinga2 stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u nagios icinga2 > /dev/null; do sleep 5; done
