#!/bin/bash

. /opt/helpers

# do not start, if no service requires local MySQL
{  [ "${ICINGA2_IDO_MYSQL_HOST}"         == "localhost" ] \
|| [ "${ICINGAWEB2_MYSQL_HOST}"          == "localhost" ] \
|| [ "${ICINGAWEB2_DIRECTOR_MYSQL_HOST}" == "localhost" ]
} || { echo "Skipping local MySQL server bootup."; sleep infinity; }

service mariadb start

# Allow any signal which would kill a process to stop server
trap "service mariadb stop" HUP INT QUIT ABRT ALRM TERM TSTP

while pgrep -u mysql mariadb > /dev/null; do sleep 5; done
