#!/bin/bash

. /opt/helpers

# Graphite writer
if evaluate_boolean "${ICINGA2_FEATURE_GRAPHITE}"; then
	echo "=> Enabling Icinga2 graphite writer"

	icinga2 feature enable graphite

	cat >/etc/icinga2/features-available/graphite.conf <<-END
	/**
	 * The GraphiteWriter type writes check result metrics and
	 * performance data to a graphite tcp socket.
	 */
	library "perfdata"
	object GraphiteWriter "graphite" {
	  host = "$ICINGA2_FEATURE_GRAPHITE_HOST"
	  port = "$ICINGA2_FEATURE_GRAPHITE_PORT"
	  enable_send_thresholds = true
	}
	END

else
	# Actively disable graphite, to not hit any weird bugs
	icinga2 feature disable graphite || true
fi
