#!/bin/bash

. /opt/helpers

if [ ! -f "/etc/cron.d/icinga/icinga-certs" ]; then
	echo "=> Copying icinga-certs cronfile for /etc/cron.d"
	
	mkdir -p /etc/cron.d/icinga
	chmod 0644 /etc/cron.d/icinga

	cat >/etc/cron.d/icinga/icinga-certs <<-END
	# If you enabled x509 module you can use the cronjobs to insert/refresh your certificates.

	#30 2 * * * 	/usr/bin/icingacli x509 import --file /etc/ssl/certs/ca-certificates.crt 2>&1
	#00 4 * * * 	/usr/bin/icingacli x509 scan --job <JOBNAME> 2>&1
	END

	chmod 0644 /etc/cron.d/icinga/icinga-certs
fi
