#!/bin/bash

. /opt/helpers

# Graphite writer
if evaluate_boolean "${ICINGA2_FEATURE_GRAPHITE}"; then
	echo "=> Enabling Icingaweb2 graphite module"

	# icingaweb-graphite
	icingacli module enable graphite

	[ -e /etc/icingaweb2/modules/graphite ] \
		|| cp -r /usr/local/share/icingaweb2/modules/graphite/templates /etc/icingaweb2/modules/graphite

	ini_set /etc/icingaweb2/modules/graphite/config.ini graphite url "${ICINGA2_FEATURE_GRAPHITE_URL}"

else
	# Actively disable graphite, to not hit any weird bugs
	icingacli module disable graphite || true
fi
