#!/bin/bash

. /opt/helpers

CNFSUFFIX=icingaweb2director
mysql_cnf_init_section \
	"${CNFSUFFIX}" \
	"${ICINGAWEB2_DIRECTOR_MYSQL_HOST}" \
	"${ICINGAWEB2_DIRECTOR_MYSQL_PORT}" \
	"${ICINGAWEB2_DIRECTOR_MYSQL_USER}" \
	"${ICINGAWEB2_DIRECTOR_MYSQL_DATA}" \
	"${ICINGAWEB2_DIRECTOR_MYSQL_PASS}"
mysql_wait \
	"${ICINGAWEB2_DIRECTOR_MYSQL_HOST}" \
	"${ICINGAWEB2_DIRECTOR_MYSQL_PORT}"

if evaluate_boolean "${ICINGA2_FEATURE_DIRECTOR}"; then

	icingacli module enable director

	# Create MySQL user on localhost or test given connection
	if [ "${ICINGAWEB2_DIRECTOR_MYSQL_HOST}" == "localhost" ]; then
		mysql_root <<-END
		  CREATE DATABASE IF NOT EXISTS ${ICINGAWEB2_DIRECTOR_MYSQL_DATA}
		    CHARACTER SET 'utf8';
		  GRANT ALL
		    ON ${ICINGAWEB2_DIRECTOR_MYSQL_DATA}.*
		    TO '${ICINGAWEB2_DIRECTOR_MYSQL_USER}'@'localhost'
		    IDENTIFIED BY '${ICINGAWEB2_DIRECTOR_MYSQL_PASS}';
		END
	elif [ -n "${MYSQL_ROOT_PASSWORD:-}" ]; then
		mysql_root <<-END
		  CREATE DATABASE IF NOT EXISTS ${ICINGAWEB2_DIRECTOR_MYSQL_DATA}
		    CHARACTER SET 'utf8';
		  GRANT ALL
		    ON ${ICINGAWEB2_DIRECTOR_MYSQL_DATA}.*
		    TO '${ICINGAWEB2_DIRECTOR_MYSQL_USER}'@'%'
		    IDENTIFIED BY '${ICINGAWEB2_DIRECTOR_MYSQL_PASS}';
		END
	fi

	mysql_test_credentials

	mysql_user \
		< /usr/local/share/icingaweb2/modules/director/schema/mysql.sql \
		>> /var/log/icingaweb2/director-schema.log \
		2>&1 || true

	ini_set /etc/icingaweb2/resources.ini director host     "${ICINGAWEB2_DIRECTOR_MYSQL_HOST}"
	ini_set /etc/icingaweb2/resources.ini director port     "${ICINGAWEB2_DIRECTOR_MYSQL_PORT}"
	ini_set /etc/icingaweb2/resources.ini director username "${ICINGAWEB2_DIRECTOR_MYSQL_USER}"
	ini_set /etc/icingaweb2/resources.ini director password "${ICINGAWEB2_DIRECTOR_MYSQL_PASS}"
	ini_set /etc/icingaweb2/resources.ini director dbname   "${ICINGAWEB2_DIRECTOR_MYSQL_DATA}"

	cat > /tmp/icinga2-api-user.conf <<-END
	object ApiUser "${ICINGA2_FEATURE_DIRECTOR_USER}" {
	  password = "${ICINGA2_FEATURE_DIRECTOR_PASS}"
	  permissions = [ "*" ]
	}
	END

	[ ! -L /etc/icinga2/conf.d/api-user.conf ] && \
		ln -sT /tmp/icinga2-api-user.conf /etc/icinga2/conf.d/api-user.conf

	ini_set /etc/icingaweb2/modules/director/kickstart.ini config endpoint "$(hostname)"
	ini_set /etc/icingaweb2/modules/director/kickstart.ini config username "${ICINGA2_FEATURE_DIRECTOR_USER}"
	ini_set /etc/icingaweb2/modules/director/kickstart.ini config password "${ICINGA2_FEATURE_DIRECTOR_PASS}"

else
	[ ! -L /etc/icinga2/conf.d/api-user.conf ] \
		|| rm /etc/icinga2/conf.d/api-user.conf
	icingacli module disable director || true
fi
