#!/bin/bash

if [ ! -z "$CUSTOM_POST_INSTALLATION_SCRIPT" ]
then 
    echo "Executing "$CUSTOM_POST_INSTALLATION_SCRIPT
    bash $CUSTOM_POST_INSTALLATION_SCRIPT
else
    echo "Environment variable CUSTOM_POST_INSTALLATION_SCRIPT is not set, will not execute any post installation script"
fi