#!/bin/bash

if [ "$(ls -A /etc/icingaweb2)" ]; then
  echo "=>/etc/icingaweb2 check OK"
else
  mkdir /etc/icingaweb2.dist/enabledModules
  cp -R /etc/icingaweb2.dist/* /etc/icingaweb2/
  chown www-data:icingaweb2 /etc/icingaweb2
  chmod 2770 /etc/icingaweb2
  find /etc/icingaweb2 -type f -name "*.ini" -exec chmod 660 {} \;
  chown -R www-data:icingaweb2 /etc/icingaweb2/*
fi

#icingaweb2
usermod -a -G icingaweb2 www-data >> /dev/null
mysql <<-END
  CREATE DATABASE IF NOT EXISTS icingaweb2;
  GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icingaweb2.* TO 'icingaweb2'@'localhost' IDENTIFIED BY '${ICINGAWEB2_PASSWORD}';
  quit
END

mysql -f icingaweb2 < /usr/share/icingaweb2/etc/schema/mysql.schema.sql >> /opt/icingaweb2-schema.log 2>&1

ICINGAADMIN_PASSWORD=`openssl passwd -1 "icinga"`

mysql <<-END
  USE icingaweb2;
  INSERT IGNORE INTO icingaweb_user (name, active, password_hash) VALUES ('icingaadmin', 1, '${ICINGAADMIN_PASSWORD}');
  quit
END

[[ ! -L /etc/icingaweb2/enabledModules/monitoring ]] \
	&& ln -sT /etc/icingaweb2/modules/monitoring /etc/icingaweb2/enabledModules/monitoring

[[ ! -L /etc/icingaweb2/enabledModules/doc ]] \
	&& ln -sT /etc/icingaweb2/modules/doc /etc/icingaweb2/enabledModules/doc

sed -i 's,icingaweb2_changeme,'${ICINGAWEB2_PASSWORD}',g' /etc/icingaweb2/resources.ini
sed -i 's,icinga2-ido-mysq_changeme,'${IDO_PASSWORD}',g' /etc/icingaweb2/resources.ini
mkdir -p /var/log/icingaweb2
chown www-data:adm /var/log/icingaweb2
