#!/bin/bash

if [ ! "$(ls -A /etc/icingaweb2)" ]; then
  echo "=> Copying fresh config-files for /etc/icingaweb2"
  cp -R /etc/icingaweb2.dist/* /etc/icingaweb2/
fi

# chown directories and files that might be coming from volumes
chmod 2770 /etc/icingaweb2
chown -R www-data:icingaweb2 /etc/icingaweb2

mkdir -p /var/log/icingaweb2
chown -R www-data:adm /var/log/icingaweb2

# enable modules
icingacli module enable monitoring
icingacli module enable doc

# grant access to DBs
mysql <<-END
  CREATE DATABASE IF NOT EXISTS icingaweb2;
  GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE VIEW, INDEX, EXECUTE ON icingaweb2.* TO 'icingaweb2'@'localhost' IDENTIFIED BY '${ICINGAWEB2_PASSWORD}';
END

mysql icingaweb2 < /usr/share/icingaweb2/etc/schema/mysql.schema.sql >> /var/log/icingaweb2/icingaweb2-schema.log 2>&1

ini_set /etc/icingaweb2/resources.ini icingaweb_db password "${ICINGAWEB2_PASSWORD}"
ini_set /etc/icingaweb2/resources.ini icinga_ido   password "${IDO_PASSWORD}"

# Write Icingaweb2 user and password to installation
ini_set /etc/icingaweb2/roles.ini Administrators users "${ICINGAWEB2_ADMIN_USER}"
mysql <<-END
  USE icingaweb2;
  INSERT IGNORE INTO icingaweb_user (name, active, password_hash) VALUES ('${ICINGAWEB2_ADMIN_USER}', 1, '${ICINGAWEB2_ADMIN_PASS_HASH}');
END
