#!/bin/bash

icingacli module enable director

# director
mysql <<-END
  CREATE DATABASE IF NOT EXISTS director CHARACTER SET 'utf8';
  GRANT ALL ON director.* TO director@localhost IDENTIFIED BY '${DIRECTOR_PASSWORD}';
END
mysql director < /etc/icingaweb2/modules/director/schema/mysql.sql >> /var/log/icingaweb2/director-schema.log 2>&1

ini_set /etc/icingaweb2/resources.ini director password "${DIRECTOR_PASSWORD}"
if [[ $(grep director /etc/icinga2/conf.d/api-users.conf) ]]; then
	echo "=> Director Icinga2 API user exists /etc/icinga2/conf.d/api-users.conf"
else
	cat /etc/icingaweb2/modules/director/director.api >> /etc/icinga2/conf.d/api-users.conf
fi
sed -i 's,directorapi,'${DIRECTOR_API_PASSWORD}',g' /etc/icinga2/conf.d/api-users.conf
ini_set /etc/icingaweb2/modules/director/kickstart.ini config endpoint "$(hostname)"
ini_set /etc/icingaweb2/modules/director/kickstart.ini config password "${DIRECTOR_API_PASSWORD}"
