#!/bin/bash

chown -R mysql:mysql /var/lib/mysql
chown -R mysql:mysql /var/log/mysql

if [ ! "$(ls -A /var/lib/mysql)" ]; then
	echo "=>MySQL datadir is empty...initializing"
	/usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
fi

/etc/init.d/mysql start
sleep 5

# Set debian-sys-maint password
mysql <<-END
  GRANT ALL PRIVILEGES ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '${DEBIAN_SYS_MAINT_PASSWORD}';
  UPDATE mysql.user SET password=PASSWORD('${DEBIAN_SYS_MAINT_PASSWORD}') WHERE user='debian-sys-maint';
  FLUSH PRIVILEGES;
END

ini_set /etc/mysql/debian.cnf client        password "${DEBIAN_SYS_MAINT_PASSWORD}"
ini_set /etc/mysql/debian.cnf mysql_upgrade password "${DEBIAN_SYS_MAINT_PASSWORD}"
