#!/bin/bash

chown -R mysql:mysql /var/lib/mysql
chown -R mysql:mysql /var/log/mysql

if [ ! "$(ls -A /var/lib/mysql)" ]; then
	echo "=>MySQL datadir is empty...initializing"
	/usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
fi

/etc/init.d/mysql start
sleep 5
